apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production-project
  namespace: argocd
spec:
  description: Production Application Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: production-app
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: '*'
    - group: ''
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
  orphanedResources:
    warn: true