apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production-app
data:
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  REACT_APP_API_URL: "http://localhost:3001"