apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

labels:
  app.kubernetes.io/part-of: production-app
  app.kubernetes.io/managed-by: argocd
